name: Post Push Checks

on:
  push:
    paths:
      - '**/*.tsx?'
      - '**/*.jsx?'
      - '**/*.json'
      - '**/*.yaml'
      - '.github/workflows/check-post-push.yml'
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v19.6.0
        uses: actions/setup-node@v3
        with:
          node-version: '19.6.0'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install
        working-directory: .

      - name: Run lint check
        run: npm run lint
        working-directory: .

      - name: Run type check
        run: npm run typeCheck
        working-directory: .
